sudo: required  # docker requires super user permission
services:
  -docker  # travis CI will install docker

# another section
before_install: # series of commands that will occur before deployment of projecvt or running tests
# use the dockerfile.dev because its a non production build and has the test suite
  - docker build -t kabilan93/Docker-react -f Dockerfile.dev .

#series of commands that needs to run when the test is to be executed
# travis will monitor the output from these commands and if it recieves a 
# status code other that 0, travis will assume that the build failed and
# the code is broken.
# the test script by default does nnot automatically exit, so add the commands
# -- -- coverage at the end of the test command
script:
  -  docker run kabilan93/Docker-react npm run test -- --coverage